addSbtPlugin("com.typesafe.play"        % "sbt-plugin"               % "2.8.1")
addSbtPlugin("org.foundweekends.giter8" % "sbt-giter8-scaffold"      % "0.11.0")
addSbtPlugin("org.scala-js"             % "sbt-scalajs"              % "1.0.1")
addSbtPlugin("org.portable-scala"       % "sbt-scalajs-crossproject" % "1.0.0")
addSbtPlugin("org.scalameta"            % "sbt-scalafmt"             % "2.3.4")
